services:

  nginx:
    build:
      target: nginx
    container_name: trf-nginx
    ports:
      - "80:80"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      MINISTRY_HOST: ministry
    networks:
      - ministry
    develop:
      watch:
        - path: ./static
          action: sync
          target: /usr/share/nginx/html

        - path: ./nginx.conf
          action: sync+restart
          target: /etc/nginx/templates/nginx.conf.template
    volumes:
      - trf-nginx-cache:/data/nginx/cache
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1/healthz || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - ministry

  ministry:
    build:
      target: ministry
    container_name: trf-ministry
    ports:
      - "8080:80"
    networks:
      - ministry
    environment:
      MINISTRY_POSTGRES_USER: "trf"
      MINISTRY_POSTGRES_PASSWORD: "trf"
      MINISTRY_POSTGRES_DB: "trf"
      MINISTRY_POSTGRES_HOST: "postgres"

      MINISTRY_SPOOFER_TYPE: mock
    develop:
      watch:
        - path: ./templates
          action: rebuild
        - path: ./cmd
          action: rebuild
        - path: ./internal
          action: rebuild 
    healthcheck:
      test: ["CMD", "/ministry", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - migrate

  migrate:
    image: migrate/migrate:v4.17.1
    restart: on-failure:5
    container_name: trf-migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - ministry
    command:
      - "-path=/migrations/"
      - "-database=postgres://trf:trf@postgres:5432/trf?sslmode=disable"
      - "up"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: trf-postgres
    ports:
      - "5432:5432"
    networks:
      - ministry
    environment:
      POSTGRES_USER: "trf"
      POSTGRES_PASSWORD: "trf"
      POSTGRES_DB: "trf"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trf"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  trf-nginx-cache:

networks:
  ministry:
