services:
  ministry:
    build: ministry
    container_name: trf-ministry
    develop:
      watch:
        - action: rebuild
          path: ministry/cmd
        - action: rebuild
          path: ministry/internal
        - action: rebuild
          path: ministry/go.mod
        - action: rebuild
          path: ministry/go.sum

        - action: sync+restart
          path: migrations
          target: /app/migrations

        - action: sync
          path: ministry/templates
          target: /app/static
    environment:
      MINISTRY_DEBUG: "true"
      MINISTRY_POSTGRES_URL: postgres://trf:trf@postgres:5432/trf?sslmode=disable
    depends_on:
      - postgres
      - minio
      - minio-setup

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: trf-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "trf"
      POSTGRES_PASSWORD: "trf"
      POSTGRES_DB: "trf"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trf"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: trf-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio-setup:
    build: minio-setup
    container_name: trf-minio-setup
    environment:
      MINIO_URL: http://minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINISTRY_PASSWORD: ministry
    depends_on:
      - minio

  nginx:
    build: nginx
    container_name: trf-nginx
    develop:
      watch:
        - action: sync
          path: nginx/static
          target: /usr/share/nginx/static
        - action: sync+restart
          path: nginx/nginx.conf.template
          target: /etc/nginx/templates/nginx.conf.template
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:80"
    environment:
      FILESERVICE_URL: http://minio:9000/trf
      EXTERNAL_PORT: 8080
    depends_on:
      - minio
      - minio-setup
