services:
  sqlfluff:
    image: sqlfluff/sqlfluff:3.0.3
    user: "${UID}:${GID}"
    working_dir: /output
    command:
      - lint
      - /sql
      - --format
      - json
      - --dialect
      - postgres
      - --write-output
      - results.json
      - --disable-progress-bar
      - --nocolor
    volumes:
      - ../../../migrations:/sql
      - ./output:/output
