name: Lint Migrations

on:
  pull_request:
    paths:
      - migrations/**
  workflow_dispatch:

jobs:
  lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint migrations
        run: ci/migrations/sqlfluff/lint.sh

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: sqlfluff-results
          path: ci/migrations/sqlfluff/output/results.json