name: Build, Test, and Push ministry

on:
  push:
    paths:
      - ci/ministry/**
      - ministry/**
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ministry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build ministry
        id: build-ministry-image
        run: |
          image=$(ci/ministry/build/build.sh)
          echo "Built ministry image: $image"
          echo "image_name=$image" >> $GITHUB_OUTPUT

      - name: Loging to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push ministry image
        run: |
          release_image=$(ci/ministry/push.sh ${{ steps.build-ministry-image.outputs.image_name }})
          echo "Pushed ministry image: $release_image"
