name: Build, Test, and Push nginx 

on:
  push:
    paths:
      - ci/nginx/**
      - nginx/**
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build 
        id: build-nginx-image
        run: |
          image=$(ci/nginx/build/build.sh)
          echo "Built nginx image: $image"
          echo "image_name=$image" >> $GITHUB_OUTPUT

      - name: Loging to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push nginx image
        run: |
          release_image=$(ci/nginx/push.sh ${{ steps.build-nginx-image.outputs.image_name }})
          echo "Pushed nginx image: $release_image"
